"""
Run this ONCE to generate a clean career_paths.csv in your datasets folder.
Usage: python generate_career_paths.py
It will create: ../datasets/career_paths.csv
"""
import pandas as pd
import os

rows = [
    # Tech
    ("WEB-DEVELOPER",          "Senior Web Developer"),
    ("WEB-DEVELOPER",          "Frontend Lead"),
    ("WEB-DEVELOPER",          "Full Stack Developer"),
    ("WEB-DEVELOPER",          "Engineering Manager"),
    ("SOFTWARE-ENGINEER",      "Senior Software Engineer"),
    ("SOFTWARE-ENGINEER",      "Tech Lead"),
    ("SOFTWARE-ENGINEER",      "Principal Engineer"),
    ("SOFTWARE-ENGINEER",      "CTO"),
    ("DATA-SCIENCE",           "Senior Data Scientist"),
    ("DATA-SCIENCE",           "ML Engineer"),
    ("DATA-SCIENCE",           "AI Research Lead"),
    ("DATA-SCIENCE",           "Head of Data"),
    ("INFORMATION-TECHNOLOGY", "Senior Developer"),
    ("INFORMATION-TECHNOLOGY", "Tech Lead"),
    ("INFORMATION-TECHNOLOGY", "Engineering Manager"),
    ("INFORMATION-TECHNOLOGY", "CTO"),
    # Business
    ("FINANCE",                "Senior Financial Analyst"),
    ("FINANCE",                "Finance Manager"),
    ("FINANCE",                "VP Finance"),
    ("FINANCE",                "CFO"),
    ("HR",                     "HR Manager"),
    ("HR",                     "HR Business Partner"),
    ("HR",                     "HR Director"),
    ("HR",                     "CHRO"),
    ("SALES",                  "Senior Sales Executive"),
    ("SALES",                  "Sales Manager"),
    ("SALES",                  "VP Sales"),
    ("SALES",                  "CSO"),
    ("BANKING",                "Senior Banker"),
    ("BANKING",                "Branch Manager"),
    ("BANKING",                "Regional Director"),
    ("BANKING",                "Head of Banking"),
    ("ACCOUNTANT",             "Senior Accountant"),
    ("ACCOUNTANT",             "Finance Controller"),
    ("ACCOUNTANT",             "Head of Accounts"),
    ("ACCOUNTANT",             "CFO"),
    ("BUSINESS-DEVELOPMENT",   "BD Manager"),
    ("BUSINESS-DEVELOPMENT",   "VP Business Development"),
    ("BUSINESS-DEVELOPMENT",   "Chief Growth Officer"),
    ("CONSULTANT",             "Senior Consultant"),
    ("CONSULTANT",             "Principal Consultant"),
    ("CONSULTANT",             "Associate Partner"),
    ("CONSULTANT",             "Partner"),
    # Creative / Media
    ("DESIGNER",               "Senior Designer"),
    ("DESIGNER",               "Design Lead"),
    ("DESIGNER",               "Creative Director"),
    ("DESIGNER",               "VP Design"),
    ("DIGITAL-MEDIA",          "Senior Media Specialist"),
    ("DIGITAL-MEDIA",          "Media Manager"),
    ("DIGITAL-MEDIA",          "Head of Digital"),
    ("DIGITAL-MEDIA",          "CMO"),
    ("PUBLIC-RELATIONS",       "Senior PR Specialist"),
    ("PUBLIC-RELATIONS",       "PR Manager"),
    ("PUBLIC-RELATIONS",       "Head of PR"),
    ("PUBLIC-RELATIONS",       "Communications Director"),
    ("ARTS",                   "Senior Artist"),
    ("ARTS",                   "Art Director"),
    ("ARTS",                   "Creative Director"),
    ("APPAREL",                "Senior Designer"),
    ("APPAREL",                "Design Manager"),
    ("APPAREL",                "Brand Director"),
    # Other
    ("HEALTHCARE",             "Senior Clinician"),
    ("HEALTHCARE",             "Medical Supervisor"),
    ("HEALTHCARE",             "Medical Director"),
    ("HEALTHCARE",             "CMO"),
    ("ENGINEERING",            "Senior Engineer"),
    ("ENGINEERING",            "Lead Engineer"),
    ("ENGINEERING",            "Engineering Director"),
    ("ENGINEERING",            "VP Engineering"),
    ("TEACHER",                "Senior Teacher"),
    ("TEACHER",                "Head of Department"),
    ("TEACHER",                "Vice Principal"),
    ("TEACHER",                "Principal"),
    ("ADVOCATE",               "Senior Advocate"),
    ("ADVOCATE",               "Associate Partner"),
    ("ADVOCATE",               "Partner"),
    ("ADVOCATE",               "Legal Director"),
    ("AVIATION",               "Senior Pilot"),
    ("AVIATION",               "Chief Pilot"),
    ("AVIATION",               "Flight Operations Manager"),
    ("AVIATION",               "Director of Operations"),
    ("CONSTRUCTION",           "Site Manager"),
    ("CONSTRUCTION",           "Project Manager"),
    ("CONSTRUCTION",           "Construction Director"),
    ("AUTOMOBILE",             "Senior Technician"),
    ("AUTOMOBILE",             "Service Manager"),
    ("AUTOMOBILE",             "Regional Director"),
    ("BPO",                    "Team Lead"),
    ("BPO",                    "Operations Manager"),
    ("BPO",                    "Senior Manager"),
    ("BPO",                    "VP Operations"),
    ("AGRICULTURE",            "Senior Agronomist"),
    ("AGRICULTURE",            "Farm Manager"),
    ("AGRICULTURE",            "Regional Agricultural Director"),
    ("FITNESS",                "Senior Trainer"),
    ("FITNESS",                "Fitness Manager"),
    ("FITNESS",                "Regional Wellness Manager"),
    ("CHEF",                   "Sous Chef"),
    ("CHEF",                   "Head Chef"),
    ("CHEF",                   "Executive Chef"),
    ("CHEF",                   "F&B Director"),
]

df = pd.DataFrame(rows, columns=["current_role", "next_role"])

out_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "datasets", "career_paths.csv")
out_path = os.path.normpath(out_path)
df.to_csv(out_path, index=False)
print(f"✅ Generated {len(df)} career path rows → {out_path}")